### ISSUE TITLE
امکان استفاده در expo

### ISSUE THREAD

**Issue by PurTahan** [tapsellorg/TapsellSDK-ReactNativeSample-New#1]
سلام
چطوری میشه تبلیغات تپسل رو تو پروژه های ری‌اکت نیتیوی که با expo ساخته میشن نشون داد؟
من مثال ها و توضیحات رو دیدم ولی متوجه نشدم آیا راهی وجود داره یا نه!

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود

پلاگین تپسل دیگه پشتیبانی نمیشه و باید از[ تپسل پلاس ](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativePlugin)استفاده کنید. اما توی تپسل پلاس هم این مشکل وجود داره. توی پلاگین نیاز دارید تا بعضی جاها برید سمت کد نیتیو و اون رو تغییر بدید. در حال حاضر این محدودیت وجود داره.

</div>
